# Generated by Django 4.1 on 2022-08-20 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e1fe16e-6222-4fa1-b9a9-05b30e1c1740'), editable=False, primary_key=True, serialize=False),
        ),
    ]
