# Generated by Django 4.1 on 2022-08-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelTable(
            name='connection',
            table='connection',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
