# Generated by Django 4.1 on 2022-08-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_options_alter_connection_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='connection',
            table=None,
        ),
    ]
